services:
  backend:
    build: .
    container_name: rewear-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - media:/app/media
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - media/
            - __pycache__/
            - "*.pyc"
            - "*.db"
            - ".git/"
            - "*.sqlite3"

  db:
    image: postgres:15
    container_name: rewear-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: rewear
      POSTGRES_PASSWORD: rewearpass
      POSTGRES_DB: rewear_db

volumes:
  media:
  postgres_data:

