services:
  backend:
    build: .
    container_name: rewear-backend
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: rewear-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER=rewear
      POSTGRES_PASSWORD=rewearpass
      POSTGRES_DB=rewear_db

volumes:
  media:
  postgres_data:

