# Generated by Django 5.2.4 on 2025-07-12 06:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand name (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, help_text='Primary color of the item', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='like_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes/favorites'),
        ),
        migrations.AddField(
            model_name='item',
            name='point_value',
            field=models.PositiveIntegerField(default=10, help_text='Points required to redeem this item (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='item',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Admin reason for rejection'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., vintage, summer, casual, designer)', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times viewed'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Accessibility description', max_length=255),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Main display image'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('bags', 'Bags'), ('activewear', 'Activewear'), ('underwear', 'Underwear'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text="Describe the item, its story, why you're sharing it"),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(help_text='e.g., S, M, L, XL, 32, 8, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('swapped', 'Swapped'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='Give your item a catchy title', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'status'], name='items_item_categor_ae2490_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_approved', 'is_featured'], name='items_item_is_appr_b42234_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'], name='items_item_created_3eaa9f_idx'),
        ),
        migrations.AddField(
            model_name='itemlike',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='items.item'),
        ),
        migrations.AddField(
            model_name='itemlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='itemlike',
            unique_together={('user', 'item')},
        ),
    ]
