# Generated by Django 5.2.4 on 2025-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemlike_alter_item_options_alter_itemimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for admin review'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Auto-approved, can be flagged for review'),
        ),
    ]
