# Generated by Django 5.2.4 on 2025-07-12 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_is_flagged_alter_item_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='featured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Explicitly rejected by admin'),
        ),
        migrations.AddField(
            model_name='item',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who rejected this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
